# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.IntegerField(max_length=12)),
                ('corp_secret', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': '\u5e94\u7528ID',
                'verbose_name_plural': '\u5e94\u7528ID',
            },
        ),
        migrations.CreateModel(
            name='Corp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_name', models.CharField(max_length=64, unique=True, verbose_name='\u4f01\u4e1a\u540d\u79f0')),
                ('corp_id', models.CharField(max_length=128, unique=True, verbose_name='\u4f01\u4e1aID')),
            ],
            options={
                'verbose_name': '\u4f01\u4e1a',
                'verbose_name_plural': '\u4f01\u4e1a',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='corp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Corp'),
        ),
        migrations.AlterUniqueTogether(
            name='agent',
            unique_together=set([('corp', 'agent_id')]),
        ),
    ]
